
version: 2
updates:

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/ci-github-notifier"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "go"
      prefix: "go"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      # Prefix all commit messages with "gh-actions"
      prefix: "gh-actions"
